{% set name = "more-itertools" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3e4748ba1aad8dba30a4886b0b1a2004f9a863837b8654e7059eebf727afa5a

build:
  number: 0
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - more_itertools
    - more_itertools.tests

about:
  home: https://github.com/erikrose/more-itertools
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'More routines for operating on iterables, beyond itertools'
  description: |
    more-itertools, additional building blocks, recipes, and routines for
    working with Python iterables.
  dev_url: https://github.com/erikrose/more-itertools
  doc_url: https://more-itertools.readthedocs.io/en/latest/api.html

extra:
  recipe-maintainers:
    - pmlandwehr
