{% set name = "more-itertools" %}
{% set version = "10.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/more-itertools/more_itertools-10.8.0.tar.gz
  sha256: f638ddf8a1a0d134181275fb5d58b086ead7c6a72429ad725c67503f13ba30bd

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - flit-core >=3.12,<4
    - pip
    - python
  run:
    - python

test:
  imports:
    - more_itertools
  commands:
    - pip check
    - python -m unittest discover --buffer -s=tests
  requires:
    - pip
  source_files:
    - tests

about:
  home: https://github.com/more-itertools/more-itertools
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: More routines for operating on iterables, beyond itertools
  description: |
    Python's itertools library is a gem - you can compose elegant solutions for a variety
    of problems with the functions it provides. In more-itertools we collect additional
    building blocks, recipes, and routines for working with Python iterables.
  dev_url: https://github.com/more-itertools/more-itertools
  doc_url: https://more-itertools.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - dbast
