{% set name = "more-itertools" %}
{% set version = "3.1.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "239089bb2722e0621a66dfa34936ab24efc846e74d45afbf5ac59b76de130a41" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - six >=1.0.0,<2.0.0

  run:
    - python
    - six >=1.0.0,<2.0.0

test:
  imports:
    - more_itertools
    - more_itertools.tests

about:
  home: https://github.com/erikrose/more-itertools
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'More routines for operating on iterables, beyond itertools'
  dev_url: https://github.com/erikrose/more-itertools
  doc_url: https://more-itertools.readthedocs.io/en/latest/api.html

extra:
  recipe-maintainers:
    - pmlandwehr
