travis:
  secure:
    BINSTAR_TOKEN: ecvFru/lXoreMc/OBxkzJCuGNFbTuUkhcS0dLliPo9Gx0zYlHk2TA7XEzKzrrgikzckInlm+5PyvJYzhOLEL2WUWsL2YigU2gA+oex8129USAsKRvSChbZ8sYbOj+/Xuh67D7/Jx9LArp/NuXXqeLy2/x5jU71PaAMT9ixqpZLf2dMtt2A21iU4GmGmPDW29Lvk9BnwOHhfw+kYkG6aSfHzRgH/35bI95JHaa3v5MtIUcVbtlsgh4apVCcgzEggXgsxCbxfjYWBOSAgCls4LVTJog0X1Hafxo/w5/ujbHJ10CvD+hQyAzejkyrg1+B1MKipucXxhP31pibOFaVrb2Apqq7Tl+k3iy9A7nmIF3oIuXg9Uy5J6Ty6VR0asuon5lyGXpRw100tFujITQ9N8HqGYbjVZqeK1jOnmBIywFr3HkyyzNXpyELjQ9/OPJR6Kbi1WU7cK6APWYAT/djKRgmy0jR1Ce4ebSm2UIf/lSHDAVcinLdLcPfL+NJpC9GepeIxtHUHPczt/60N9yYQ+LY9TGOLB1v6EhjWGajjLCsSjQD5PgFqAX8JzHXUpP5tYAC/IM56/snizLcn4uahcyn+EFLtlBWyiY/T36OH33lGH3Q9OHUu8S4hgu4JogAp6zk1ElTOKtjC3evl8VxJ+QpTtSGBbYb7htzkPl/ad2Bs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
