travis:
  secure:
    BINSTAR_TOKEN: rDfBaSw4CXvMcMbZMSFiamgjF9rqwOh7LEw1AGS1CubjqoSa8DK9bAW2J/8RLlScq234w5USWATDbc2J4L1snTty5oa4xh3ZIvLX81oU2zgDywHaNYMpwf8gk7+lrHxE7P+Q8ubDn/l2RF+oD9smUOKvJpWnjG8a720rj9flk3no/wWyzndoIDpcQzE4lyCMN7KY0cpgAvVD4qsgIziyhiZErghAQdrCdAjL0q8dBA9aRfOKG6pDZe0PlAJhlbPkLLWjY+MwTLyGaJykcaf82TUEmiVpU5SensbpNTmYBIETTYdDEd4L2mcDnGEak+PMAN2FjOpz11ml10aOoFC2K/0urO3N1xUQHoNt54IOiED+r7yt6mh+3oDfIQgxiCItqfkvYNSFSBx6q1KBJ0/w3wuYTb+ckFD4RJQI99EgoVYgPHZH3raN3xlY56p+kl1G5YA1dY0h6Cw50iPNqxlciyTw++MksamH6bnmDv/rR8bDnjBCr1G+L0MF84Qu3wtI25bwVS0SKYmcq/o9u0SXVGhm4BLYLgMZJLM5vMVBie8v4Sfobyv/Xv1dBKRmSgIiXA6uRGhoUm9ByfgHWmGsu4tTdvY0GAuxT/xcO6MWIKAUYcmsju75lABI/cdLB+Zvr9/IsseCZ9z5d02J2S3Ywcb9b4FMs9gtpo78JDsPDdk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
